### ISSUE TITLE
TransactionScope

### ISSUE THREAD

**Issue by Fjomp08** [sakopov/Dapper.AmbientContext#6]
What is the main difference between using Dapper.AmbientContext and using TransactionScope? The AmbientContext seems to have the same functionality as TransactionScope.

**Comment by sakopov** [comment]
Ambient context provides access to active database connection and transaction to anything that needs to execute 1 or more queries, typically spread out across various repositories, as a single unit of work and without explicitly passing transactions and connections around. Hence, the term "ambient". I'll try to add some samples to this project to demonstrate how it's used, in case the wiki isn't making it clear.

**Comment by sakopov** [comment]
Please look at [sample projects](https://github.com/sakopov/Dapper.AmbientContext/tree/master/samples) for more info.
