### ISSUE TITLE
AmbientDbContext additional data

### ISSUE THREAD

**Issue by vincentparrett** [sakopov/Dapper.AmbientContext#8]
Hi

This library almost looks perfect for what I need, however there is one feature missing. In my current code (which has a dbcontext, dbcontextfactory, dbconnectionfactory) I pass in information about what db type it is through the connectionfactory (my app supports sqlserver and postgresql) which flows down to the dbcontext. The reason for this is differences in sql needed for different db server types. 

Is there any interest in adding a string property (Info) to the IDbConnectionFactory, IAmbientDbContext, and AmbientDbContext? I would be happy to create a PR for this.

**Comment by sakopov** [comment]
Are you looking to do something like this?

```csharp
using (var ambientContext = _ambientContextFactory.Create(dbtype: "Postgres"))
{
    await _anUpdateQuery.ExecuteAsync();
    await _anInsertQuery.ExecuteAsync();

    ambientContext.Commit();
}
```
Where the connection factory looks like:

```csharp
public class HybridConnectionFactory : IDbConnectionFactory
{
    private readonly string _connectionString;

    public HybridConnectionFactory(string connectionString)
    {
        _connectionString = connectionString;
    }

    public IDbConnection Create(string dbType)
    {
        if (dbType = "Postgres")
           return new PostgreSqlConnection(_connectionString);
        else
           return new SqlConnection(_connectionString);
    }
}
```

We could probably look into adding the ability to pass parameters to `IDbConnectionFactory` from `IAmbientDbContextFactory` via `Create` method, if this is what you're looking for.

**Comment by vincentparrett** [comment]
Not quite, I'm only ever connecting to one db, I just need to know what type it is. I already have a connection factory which handles that (I pass the db type in the constructor). What I need further down in my repositories, is to know what sort of db the dbcontext is for, so I can generate the correct sql.

**Comment by sakopov** [comment]
How about creating a context for your database connection that you can use in your queries? 

Consider the following database connection factory implementations for SQL Server and Postgres.

```csharp
public class PostgresDbConnectionFactory : IDbConnectionFactory
{
    private readonly string _connectionString;

    public PostgresDbConnectionFactory(string connectionString)
    {
        _connectionString = connectionString;
    }

    public IDbConnection Create()
    {
        return new NpgsqlConnection(_connectionString);
    }
}

public class SqlServerDbConnectionFactory : IDbConnectionFactory
{
    private readonly string _connectionString;

    public SqlServerDbConnectionFactory(string connectionString)
    {
        _connectionString = connectionString;
    }

    public IDbConnection Create()
    {
        return new SqlConnection(_connectionString);
    }
}
```

Now create a context that derives type type of database being used from the type of database connection factory that's in use.

```csharp
public class DbConnectionContext
{
    private readonly IDbConnectionFactory _dbConnectionFactory;

    public DbConnectionContext(IDbConnectionFactory dbConnectionFactory)
    {
        _dbConnectionFactory = dbConnectionFactory;
    }

    public bool IsPostgres => _dbConnectionFactory.GetType() == typeof(PostgresDbConnectionFactory);

    public bool IsSqlServer => _dbConnectionFactory.GetType() == typeof(SqlServerDbConnectionFactory);
}
```

If you inject `DbConnectionContext` into your queries and use `IsPostgres` or `IsSqlServer` properties you'll be able to figure out type of database connection you're dealing with and structure your queries accordingly.

**Comment by vincentparrett** [comment]
I was hoping that it would be just on the IAmbientDbContextQueryProxy  or on the IAmbientDbContextLocator so I wouldn't have to inject something else. It's not a big deal, I can work around it for now. I'm exploring various options, not 100% sure I want to use the ambient context pattern, so I'm trying out a few options. I'll close this for now, might revisit in the future.

**Comment by sakopov** [comment]
You could explore having a separate query class for each database type instead of having a single class that does both. This is a fairly common pattern in supporting multiple database engines. It would eliminate the need for the context. All you'd be doing is injection either SQL queries or Postgres queries at startup.

I'm hesitant to add this mainly because you can work around this by either doing what i mentioned above or deriving a context that you can inject. Adding this to `IAmbientDbContextQueryProxy` doesn't seem ideal to me because its main function is a proxy for Dapper queries and we'd be breaking single-responsibility principle here. Pretty much the same issue with `IAmbientDbContextLocator` which is just a service locator. It could be added to IAmbientDbContext, however, you'd have to do some nasty casts to be able to access it from the queries and this is by design as I didn't want consumers tinkering with the context itself and use the query proxy instead.
